### ISSUE TITLE
Does not work with newer versions of ruby

### ISSUE THREAD

**Issue by mrinterweb** [rhomobile/rhodes#306]
I am using the latest rhodes gem and ruby 2.1.0. It fails by trying to load iconv (which has been deprecated for a while).

```
/Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- iconv (LoadError)
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/activesupport-2.3.18/lib/active_support/inflector.rb:3:in `<top (required)>'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/activesupport-2.3.18/lib/active_support/core_ext/integer/inflections.rb:1:in `<top (required)>'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/activesupport-2.3.18/lib/active_support/core_ext/integer.rb:2:in `<top (required)>'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/activesupport-2.3.18/lib/active_support/core_ext.rb:8:in `block in <top (required)>'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/activesupport-2.3.18/lib/active_support/core_ext.rb:8:in `each'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/activesupport-2.3.18/lib/active_support/core_ext.rb:8:in `<top (required)>'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/activesupport-2.3.18/lib/active_support.rb:56:in `<top (required)>'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/rhodes-3.5.1.12/res/generators/rhogen.rb:6:in `<top (required)>'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /Users/myname/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/rhodes-3.5.1.12/bin/rhogen:5:in `<top (required)>'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/rhodes-3.5.1.12/bin/rhodes:4:in `load'
    from /Users/myname/.rvm/gems/ruby-2.1.0/gems/rhodes-3.5.1.12/bin/rhodes:4:in `<top (required)>'
    from /Users/myname/.rvm/gems/ruby-2.1.0/bin/rhodes:23:in `load'
    from /Users/myname/.rvm/gems/ruby-2.1.0/bin/rhodes:23:in `<main>'
```

**Comment by jtara** [comment]
As of 5.0-SP3 candidate, at least from commit b9eb1217 installing `iconv` is no longer needed.

**Comment by mwlang** [comment]
I encountered this installing rhodes to Ruby 2.1 and Ruby 2.2 on OSX today.  

    gem install iconv

seems to resolve the issue as @jtara pointed out above.

**Comment by alex-epifanoff** [comment]
Latest RMS versions are working OK with Ruby 2.3.x
