### ISSUE TITLE
rhodes 6 UserGestures incompatible with android <= 4.1 devices

### ISSUE THREAD

**Issue by leonardofalk** [rhomobile/rhodes#957]
Environment:
```
Windows 10 Pro
Rhodes version: 6.0.30
JDK: 1.8.0u162
Ruby 2.3.3
Android NDK 15c
Android SDK 4.4.2
```

On file `rhodes\platform\android\Rhodes\src\com\rhomobile\rhodes\webview\WebSettingsProviderBase.java` I guess the method `setMediaPlaybackRequiresUserGesture` doesn't exist in android 4.1.x (it may happen on lower versions, I haven't tested them all yet), commenting the line seems to fix it for now and the app running ok so far.

logcat:

```
I/APP     ( 1409): W 05/15/2018 12:14:56:430 00000581       RhodesActivity| Error loading RhoElements configuraiton (IllegalArgumentException): Cannot get com.rhomobile.rhodes.R$raw.config
I/dalvikvm( 1409): Could not find method android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture, referenced from method com.rhomobile.rhodes.webview.WebSettingsProviderBase.fillSettings
W/dalvikvm( 1409): VFY: unable to resolve virtual method 11871: Landroid/webkit/WebSettings;.setMediaPlaybackRequiresUserGesture (Z)V
D/dalvikvm( 1409): VFY: replacing opcode 0x6e at 0x002c
D/AndroidRuntime( 1409): Shutting down VM
W/dalvikvm( 1409): threadid=1: thread exiting with uncaught exception (group=0x40a122a0)
E/AndroidRuntime( 1409): FATAL EXCEPTION: main
E/AndroidRuntime( 1409): java.lang.NoSuchMethodError: android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.webview.WebSettingsProviderBase.fillSettings(WebSettingsProviderBase.java:25)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.webview.WebSettingsProviderEclair.fillSettings(WebSettingsProviderEclair.java:11)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.webview.WebSettingsProviderEclairMR1.fillSettings(WebSettingsProviderEclairMR1.java:11)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.webview.WebSettingsProviderHoneycombMR1.fillSettings(WebSettingsProviderHoneycombMR1.java:11)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.webview.WebSettingsProviderJellyBean.fillSettings(WebSettingsProviderJellyBean.java:10)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.webview.GoogleWebView.applyWebSettings(GoogleWebView.java:94)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.webview.GoogleWebView.setConfig(GoogleWebView.java:116)
E/AndroidRuntime( 1409): 	at com.rho.webview.WebViewSingleton.onWebViewCreated(WebViewSingleton.java:376)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.extmanager.RhoExtManagerImpl.createWebView(RhoExtManagerImpl.java:350)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.extmanager.RhoExtManagerImpl.onCreateActivity(RhoExtManagerImpl.java:912)
E/AndroidRuntime( 1409): 	at com.rhomobile.rhodes.RhodesActivity.onCreate(RhodesActivity.java:326)
E/AndroidRuntime( 1409): 	at android.app.Activity.performCreate(Activity.java:5008)
E/AndroidRuntime( 1409): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
E/AndroidRuntime( 1409): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
E/AndroidRuntime( 1409): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
E/AndroidRuntime( 1409): 	at android.app.ActivityThread.access$600(ActivityThread.java:130)
E/AndroidRuntime( 1409): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
E/AndroidRuntime( 1409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1409): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1409): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 1409): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1409): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1409): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 1409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 1409): 	at dalvik.system.NativeStart.main(Native Method)
```

Also, before this error I was getting this other error, dunno if it's related:

```
E/AndroidRuntime( 1148): FATAL EXCEPTION: main
E/AndroidRuntime( 1148): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 1148): 	at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 1148): 	at java.lang.Class.newInstance(Class.java:1319)
E/AndroidRuntime( 1148): 	at android.app.Instrumentation.newApplication(Instrumentation.java:982)
E/AndroidRuntime( 1148): 	at android.app.Instrumentation.newApplication(Instrumentation.java:967)
E/AndroidRuntime( 1148): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
E/AndroidRuntime( 1148): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4124)
E/AndroidRuntime( 1148): 	at android.app.ActivityThread.access$1300(ActivityThread.java:130)
E/AndroidRuntime( 1148): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
E/AndroidRuntime( 1148): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1148): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1148): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 1148): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1148): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1148): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 1148): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 1148): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1148): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:    37 cannot locate 'getsid'...
E/AndroidRuntime( 1148): 
E/AndroidRuntime( 1148): 	at java.lang.Runtime.loadLibrary(Runtime.java:370)
E/AndroidRuntime( 1148): 	at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime( 1148): 	at com.rhomobile.rhodes.NativeLibraries.load(NativeLibraries.java:8)
E/AndroidRuntime( 1148): 	at com.rhomobile.rhodes.RhodesApplication.<clinit>(RhodesApplication.java:105)
E/AndroidRuntime( 1148): 	... 16 more
```

Turned out we had also to set undefined constants HAVE_GETSID and HAVE_MALLOC_USABLE_SIZE, over rhodes' files.

**Comment by alex-epifanoff** [comment]
@leonardofalk  We're dropping support for obsolete Androids, so some incompatibilities are possible. Any KitKat version should work fine though.

**Comment by leonardofalk** [comment]
@alex-epifanoff 
Oh I see

Indeed kitkat up to oreo seems fine, I thought it was some regression problem, anyway I'm gonna close this one.
